### ISSUE TITLE
NoMethodError undefined method `example_id' for polymorphic association

### ISSUE THREAD

**Issue by drwhirst** [json-api/json-api#1473]
I am getting a strange error. It seems that the serializer is looking for an attribute on an association called 'example_id' which doesn't exist and is subsequently throwing the above error.

My serializers: 

```
class ExampleSerializer
  include FastJsonapi::ObjectSerializer
  attributes :body
  has_many :concepts, record_type: :concept
  has_many :keywords
  has_many :entities
end

```
```
class ConceptSerializer
  include FastJsonapi::ObjectSerializer
  attributes :label, :synonyms, :relevance, :mandatory

  belongs_to :example, serializer: ExampleSerializer
end
```

and  my controller method: 

```
def show
    options = {include: [:concepts, :keywords, :entities]}
    render json: ExampleSerializer.new(@example, options).serialized_json, status: :ok
end
```

Finally, the stack trace:

```
app/controllers/examples_controller.rb:14:in `show'
Started GET "/examples/1" for ::1 at 2020-05-05 17:05:25 -0400
Processing by ExamplesController#show as */*
  Parameters: {"id"=>"1"}
  Example Load (0.2ms)  SELECT "examples".* FROM "examples" WHERE "examples"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/examples_controller.rb:45:in `set_example'
   (0.1ms)  SELECT "concepts"."id" FROM "concepts" WHERE "concepts"."conceptable_id" = $1 AND "concepts"."conceptable_type" = $2  [["conceptable_id", 1], ["conceptable_type", "Example"]]                                            
  ↳ app/controllers/examples_controller.rb:14:in `show'
   (0.1ms)  SELECT "keywords"."id" FROM "keywords" WHERE "keywords"."keywordable_id" = $1 AND "keywords"."keywordable_type" = $2  [["keywordable_id", 1], ["keywordable_type", "Example"]]                                            
  ↳ app/controllers/examples_controller.rb:14:in `show'
   (0.1ms)  SELECT "entities"."id" FROM "entities" WHERE "entities"."entitable_id" = $1 AND "entities"."entitable_type" = $2  [["entitable_id", 1], ["entitable_type", "Example"]]                                                    
  ↳ app/controllers/examples_controller.rb:14:in `show'
  Concept Load (0.2ms)  SELECT "concepts".* FROM "concepts" WHERE "concepts"."conceptable_id" = $1 AND "concepts"."conceptable_type" = $2  [["conceptable_id", 1], ["conceptable_type", "Example"]]                                   
  ↳ app/controllers/examples_controller.rb:14:in `show'
Completed 500 Internal Server Error in 32ms (ActiveRecord: 7.9ms | Allocations: 19234)


  
NoMethodError (undefined method `example_id' for #<Concept:0x00007efc3c32c118>):
  
app/controllers/examples_controller.rb:14:in `show'
```

Any help resolving this issue would be greatly appreciated. I am new to the fast json api gem. 

Thanks!

**Comment by jelhan** [comment]
This issue doesn't seem to be about the JSON:API specification itself. It seems to be related to a specific implementation of the specification ([fast_jsonapi](https://github.com/Netflix/fast_jsonapi)?). If the question is still relevant for you, I would recommendto ask it in the GitHub repository for that implementation or on [StackOverflow](https://stackoverflow.com/).
